name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - run: yarn install --frozen-lockfile
      - run: yarn add @kirbic/openapi-types@latest
        if: github.event_name == 'repository_dispatch'
      - run: node -e "console.log('::set-output name=version::' + require('@kirbic/openapi-types/package').version)"
        id: openapi_types
      - run: yarn run update-endpoints
        env:
          VERSION: ${{ steps.openapi_types.outputs.version }}
      - run: yarn run build
      - run: yarn run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
